import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  viewport: "width=device-width, initial-scale=1",
  charset: "utf-8",
  favicon: "/favicon.ico",
  themeColor: "#000000",
  colorScheme: "auto",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
